services:
  apache:
    container_name: fluffy-disco-cms-apache
    image: php:8.1.16-apache
    ports:
      - "9090:80"
    networks:
      - database
    volumes:
      - ./src/:/var/www/html/

  mariadb:
    container_name: fluffy-disco-cms-mariadb
    image: mariadb
    volumes:
      - db-data:/etc/data
    environment:
      - MARIADB_ROOT_PASSWORD=qwerty
    networks:
      - database

  phpmyadmin:
    container_name: fluffy-disco-cms-phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - database
    ports:
      - "9091:80"
    environment:
      - PMA_HOST=fluffy-disco-cms-mariadb

volumes:
  db-data:

networks:
  database: {}
